# [BASH IGNORE]

FROM docker.is.localnet:5000/amd/18.04:ros
MAINTAINER Vincent Berenz <vincentberenz@tuebingen.mpg.de>

# [/BASH IGNORE]

########################################################################

#[BASH UPDATE]
RUN python3 -m pip install pin

#[/BASH UPDATE]
