# [BASH IGNORE]

FROM docker.is.localnet:5000/amd/16.04:core
MAINTAINER Vincent Berenz <vincentberenz@tuebingen.mpg.de>

# [/BASH IGNORE]

# snap, for installing some of the packages below
RUN apt install snapd

# Install Visual Studio Code editor.
RUN snap install code --classic # Visual studio code editor

